- src/main/java/com/medspace/application/service/ClinicService.java
- src/main/java/com/medspace/application/usecase/clinic/CreateClinicUseCase.java
- src/main/java/com/medspace/application/usecase/clinic/DeleteClinicByIdUseCase.java
- src/main/java/com/medspace/application/usecase/clinic/GetAllClinicsUseCase.java
- src/main/java/com/medspace/application/usecase/clinic/GetClinicByIdUseCase.java
- src/main/java/com/medspace/domain/model/Clinic.java
- src/main/java/com/medspace/domain/repository/ClinicRepository.java
- src/main/java/com/medspace/infrastructure/dto/CreateClinicDTO.java
- src/main/java/com/medspace/infrastructure/entity/ClinicEntity.java
- src/main/java/com/medspace/infrastructure/mapper/ClinicMapper.java
- src/main/java/com/medspace/infrastructure/repository/ClinicRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/rest/ClinicController.java
This PR implements the `Clinic` model following CLEAN architecture standards. It includes base use cases for creating, listing, and deleting clinics, as well as implements a `ClinicController` to handle HTTP requests.
The model is implemented according to this [design](https://drawsql.app/teams/jose-luis-team/diagrams/medspace)
It is part of this Jira [task](https://paez-tec.atlassian.net/browse/MED-75?atlOrigin=eyJpIjoiYjI5MGZmMzJmNDFhNDY0ODlhYTk1YjFhMDcyYjViMzEiLCJwIjoiaiJ9)
**Follow up:** Link the newly created `Clinic` entity to the already implemented `User` entity, so that each landlord has many clinics. To be implemented in a new PR.
Implemented entity:
- `Clinic`
Implemented use cases:
- `CreateClinicUseCase` 
- `GetAllClinicsUseCase` 
- `GetClinicByIdUseCase` 
- …
> Feature: Setup clinic resources

- src/main/java/com/medspace/application/service/ClinicAvailabilityService.java
- src/main/java/com/medspace/application/usecase/clinicAvailability/GetAvailabilitiesByClinicIdUseCase.java
- src/main/java/com/medspace/application/usecase/clinicEquipment/GetEquipmentsByClinicIdUseCase.java
- src/main/java/com/medspace/domain/model/Clinic.java
- src/main/java/com/medspace/domain/model/ClinicAvailability.java
- src/main/java/com/medspace/domain/repository/ClinicAvailabilityRepository.java
- src/main/java/com/medspace/domain/repository/ClinicEquipmentRepository.java
- src/main/java/com/medspace/domain/repository/ClinicPhotoRepository.java
- src/main/java/com/medspace/domain/repository/ClinicRepository.java
- src/main/java/com/medspace/infrastructure/dto/CreateClinicAvailabilityDTO.java
- src/main/java/com/medspace/infrastructure/dto/CreateClinicPhotoDTO.java
- src/main/java/com/medspace/infrastructure/dto/GetClinicAvailabilityDTO.java
- src/main/java/com/medspace/infrastructure/repository/ClinicAvailabilityRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/repository/ClinicEquipmentRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/repository/ClinicPhotoRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/repository/ClinicRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/rest/ClinicAvailabilityController.java
- src/main/java/com/medspace/infrastructure/rest/ClinicController.java
- src/main/java/com/medspace/infrastructure/rest/ClinicEquipmentController.java
- src/main/java/com/medspace/infrastructure/rest/ClinicPhotoController.java
This PR updates the clinic files to conform to the Java format standards
Manually tested the implemented endpoints to validate they still work
> Refactor: Use redhat Java formatter

- .gitignore
- .vscode/settings.json
- pom.xml
- src/main/java/com/medspace/infrastructure/rest/UserController.java
- src/main/java/com/medspace/infrastructure/rest/annotations/AnalystOnly.java
- src/main/java/com/medspace/infrastructure/rest/annotations/LandlordOnly.java
- src/main/java/com/medspace/infrastructure/rest/annotations/TenantOnly.java
- src/main/java/com/medspace/infrastructure/rest/annotations/UserOnly.java
- src/main/java/com/medspace/infrastructure/rest/context/RequestContext.java
- src/main/java/com/medspace/infrastructure/rest/filters/FirebaseAuthFilter.java
- src/main/java/com/medspace/infrastructure/rest/filters/UserFilter.java
- src/main/java/com/medspace/lib/FirebaseInitializer.java
This PR implements a Firebase authentication integration for the backend, along with a middleware that extracts the authenticated user's ID from the token and attaches it to the request object. This ensures secure, user-specific handling of requests across the application.
- Created a Firebase admin configuration for verifying ID tokens.
- Added `UserFilter`, `FirebaseAuthFilter` to validate incoming requests and add metadata to request
- Applied annotations to protected routes to enforce authenticated access.
- Ensure that `firebase-service-account.json` exists on resources folder
> Integrate Firebase Authentication and Middleware for User ID Injection

- src/main/java/com/medspace/application/service/UserService.java
- src/main/java/com/medspace/application/usecase/user/CreateUserUseCase.java
- src/main/java/com/medspace/domain/model/User.java
- src/main/java/com/medspace/domain/repository/UserRepository.java
- src/main/java/com/medspace/infrastructure/dto/CreateUserDTO.java
- src/main/java/com/medspace/infrastructure/entity/UserEntity.java
- src/main/java/com/medspace/infrastructure/mapper/UserMapper.java
- src/main/java/com/medspace/infrastructure/repository/UserRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/rest/UserController.java
- src/main/java/com/medspace/infrastructure/rest/context/RequestContext.java
- src/main/java/com/medspace/infrastructure/rest/filters/AnalystFilter.java
- src/main/java/com/medspace/infrastructure/rest/filters/FirebaseAuthFilter.java
- src/main/java/com/medspace/infrastructure/rest/filters/LandlordFilter.java
- src/main/java/com/medspace/infrastructure/rest/filters/TenantFilter.java
This PR implements the integration of the existing user table with Firebase Authentication by adding `firebaseUid`  to the `User` model and introduces filters for distinguishing between different user types.
- Integrated Firebase Auth with the user table to ensure synchronization between authentication and user records  
- Added filters for user types to improve query and management efficiency  
- Refactored related code to support new authentication flow and filtering logic
> Integrate Firebase Auth with user table and add user type filters

- src/main/resources/application.properties
Added cors to application.properties
```
quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=/.*/
```
> chore(CORS):Add cors rules to allow any origin when in dev mode

- src/main/java/com/medspace/application/service/ReviewService.java
- src/main/java/com/medspace/application/usecase/review/AssignReviewToAuthorUseCase.java
- src/main/java/com/medspace/application/usecase/review/CreateReviewUseCase.java
- src/main/java/com/medspace/application/usecase/review/DeleteReviewByIdUseCase.java
- src/main/java/com/medspace/application/usecase/review/GetAllReviewsUseCase.java
- src/main/java/com/medspace/application/usecase/review/GetReviewByIdUseCase.java
- src/main/java/com/medspace/domain/model/Review.java
- src/main/java/com/medspace/domain/model/User.java
- src/main/java/com/medspace/domain/repository/ReviewRepository.java
- src/main/java/com/medspace/infrastructure/dto/review/CreateReviewDTO.java
- src/main/java/com/medspace/infrastructure/dto/review/ReviewResponseDTO.java
- src/main/java/com/medspace/infrastructure/entity/ReviewEntity.java
- src/main/java/com/medspace/infrastructure/entity/UserEntity.java
- src/main/java/com/medspace/infrastructure/mapper/ReviewMapper.java
- src/main/java/com/medspace/infrastructure/repository/ReviewRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/rest/ReviewController.java
- src/main/java/com/medspace/infrastructure/rest/UserController.java
This PR implements the Review model, following CLEAN architecture coding standards. It allows the API to create, read, and delete Review models.
The model is implemented according to this [design](https://drawsql.app/teams/jose-luis-team/diagrams/medspace)
It is part of this Jira [task](https://paez-tec.atlassian.net/jira/software/projects/MED/boards/2?assignee=632bc9fe61dbef2805bd33aa&selectedIssue=MED-77)
Implemented entity:
**Review**
Implemented use cases:
AssignEquipmentToClinicUseCase
CreateReviewUseCase
DeleteReviewByIdUseCase
GetReviewByIdUseCase
GetAllReviewsUseCase
Update ReviewController with the following endpoints:
GET /reviews- Returns a list of all Reviews 
GET /reviews/{id}/- Returns the Review with the given id
Create ReviewController with the following endpoints:
POST …
> Add Review model

- src/main/java/com/medspace/application/service/PaymentService.java
- src/main/java/com/medspace/application/usecase/payment/CreatePaymentUseCase.java
- src/main/java/com/medspace/application/usecase/payment/DeletePaymentByIdUseCase.java
- src/main/java/com/medspace/application/usecase/payment/GetPaymentByIdUseCase.java
- src/main/java/com/medspace/application/usecase/payment/GetPaymentsByRentAgreementIdUseCase.java
- src/main/java/com/medspace/application/usecase/payment/UpdatePaymentStatusUseCase.java
- src/main/java/com/medspace/domain/model/Payment.java
- src/main/java/com/medspace/domain/repository/PaymentRepository.java
- src/main/java/com/medspace/infrastructure/dto/CreatePaymentDTO.java
- src/main/java/com/medspace/infrastructure/dto/PaymentResponseDTO.java
- src/main/java/com/medspace/infrastructure/entity/PaymentEntity.java
- src/main/java/com/medspace/infrastructure/mapper/PaymentMapper.java
- src/main/java/com/medspace/infrastructure/repository/PaymentRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/rest/PaymentController.java
This PR adds payment entity, authentication and authorization to all Payment resources. It ensures that only authenticated users can create and view payments, and that users can only access payments related to their rent agreements (stubbed for now).
Previously, payment endpoints were not protected, allowing any user to access or modify payment data. This PR secures the endpoints by requiring authentication and stubs ownership checks for future integration with rent agreement logic.
- Injected request context and user authentication into `PaymentController`.
- Added stubbed authorization checks in all Payment use cases.
- Exposed only the necessary endpoints:
- `POST /payments`
- `GET /payments/{id}`
- `GET /payments/rent-agreement/{rentAgreementId}`
- Added DTOs for request and response …
> feature(payment): add payment resource with authentication

- src/main/java/com/medspace/application/service/TenantFavoriteClinicService.java
- src/main/java/com/medspace/domain/model/User.java
- src/main/java/com/medspace/domain/repository/TenantFavoriteClinicRepository.java
- src/main/java/com/medspace/infrastructure/dto/CreateTenantFavoriteClinicDTO.java
- src/main/java/com/medspace/infrastructure/dto/review/CreateReviewDTO.java
- src/main/java/com/medspace/infrastructure/mapper/ReviewMapper.java
- src/main/java/com/medspace/infrastructure/repository/TenantFavoriteClinicRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/rest/NotificationController.java
- src/main/java/com/medspace/infrastructure/rest/ReviewController.java
- src/main/java/com/medspace/infrastructure/rest/TenantFavoriteClinicController.java
This PR removes the unused dependencies in the java files
> Hotfix: Unused dependencies

- src/main/java/com/medspace/application/usecase/rentRequest/CreateRentRequestUseCase.java
- src/main/java/com/medspace/domain/repository/RentRequestRepository.java
- src/main/java/com/medspace/infrastructure/repository/RentRequestRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/rest/RentRequestController.java
The POST endpoint `/rent-requests` was not working because the clinicId and the userId was not being set in the insert method of the repository. This PR updates the controller to send the appropriate ids to the useCase, and the Repository uses these ids to fetch the required entities.
The endpoint is now working:
> Hotfix: Fix POST request in Rent Request

- src/main/resources/import.sql
> feature(User):Create test users on lauch app

- src/main/java/com/medspace/infrastructure/dto/CreateUserDTO.java
- src/main/java/com/medspace/infrastructure/rest/UserController.java
This pull request enhances user creation validation logic for TENANT user types and improves data safety in the CreateUserDTO class:
> fix(user-controller): fix create tenant validation

- src/main/java/com/medspace/domain/model/Clinic.java
- src/main/java/com/medspace/infrastructure/rest/ClinicController.java
This PR updates the ENUM for clinic category so that it has the exact same options as the frontend app.
> Feature: Standardize Clinic categories in front and back

- src/main/java/com/medspace/domain/model/Clinic.java
- src/main/java/com/medspace/infrastructure/dto/CreateClinicDTO.java
- src/main/java/com/medspace/infrastructure/entity/ClinicEntity.java
- src/main/java/com/medspace/infrastructure/mapper/ClinicMapper.java
This PR adds a description field to the Clinic entity and model, to be aligned with the mysql design of db
> Feature: Add description to Clinic model

- src/main/java/com/medspace/application/service/ReviewService.java
- src/main/java/com/medspace/application/usecase/review/CreateReviewUseCase.java
- src/main/java/com/medspace/application/usecase/review/DeleteReviewByIdUseCase.java
- src/main/java/com/medspace/infrastructure/dto/review/CreateReviewDTO.java
- src/main/java/com/medspace/infrastructure/rest/ReviewController.java
This PR modifies all the Review resources to be aware of the authentication context provided by Firebase. It adds validation to verify that the requester is logged in as the appropriate type of user, and that it is owner of the resources they want to modify.
Context
Before this PR, any user could make changes to the review related entities without providing credentials. The PR adds security by ensuring authentication and authorization.
Changes
Added corresponding authorization filters and injected request context to:
ReviewController
Updated the Create and Delete, and Update use cases
CreateReviewUseCase
DeleteReviewUseCase
**POST /reviews** 
**POST /reviews  without auth**
**DELETE /reviews** 
**DELETE /reviews  without auth**
> Refactor: Add authentication to Review resources

- src/main/java/com/medspace/application/service/ClinicService.java
- src/main/java/com/medspace/application/service/ReviewService.java
- src/main/java/com/medspace/application/service/TenantFavoriteClinicService.java
- src/main/java/com/medspace/application/usecase/clinic/GetAllClinicsUseCase.java
- src/main/java/com/medspace/application/usecase/clinic/GetClinicByIdUseCase.java
- src/main/java/com/medspace/application/usecase/review/AssignReviewToClinicUseCase.java
- src/main/java/com/medspace/application/usecase/review/CreateReviewUseCase.java
- src/main/java/com/medspace/domain/model/Clinic.java
- src/main/java/com/medspace/domain/model/Review.java
- src/main/java/com/medspace/domain/repository/ReviewRepository.java
- src/main/java/com/medspace/infrastructure/dto/CreateClinicDTO.java
- src/main/java/com/medspace/infrastructure/dto/CreateTenantFavoriteClinicDTO.java
- src/main/java/com/medspace/infrastructure/dto/GetClinicDTO.java
- src/main/java/com/medspace/infrastructure/dto/review/CreateReviewDTO.java
- src/main/java/com/medspace/infrastructure/entity/ClinicEntity.java
- src/main/java/com/medspace/infrastructure/entity/ReviewEntity.java
- src/main/java/com/medspace/infrastructure/mapper/ClinicMapper.java
- src/main/java/com/medspace/infrastructure/mapper/ReviewMapper.java
- src/main/java/com/medspace/infrastructure/repository/ReviewRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/rest/ClinicController.java
- src/main/java/com/medspace/infrastructure/rest/ReviewController.java
- src/main/java/com/medspace/infrastructure/rest/TenantFavoriteClinicByUserController.java
This PR introduces new Clinic fields: 
- `availableFromDate`
- `availableToDate`
These fields will be useful when filtering clinics by specific dates. In addition, it adds a de-normalized relation between `Clinic` and `Review`, so that retrieving reviews by clinic id is easier.
- Add date fields to Clinic model and entity
- Add reviews field to Clinic entity, via a one-to-many relationship between Clinic and Review
- Introduce `GetClinicDTO` to retrieve Clinic data and average rating when making GET Clinic requests
- Added methods to calculate average rating of Clinic in `ClinicService`
The DTO returns the expected data in all endpoints:
**GET /clinics**
**GET /clinics/{id}**
> Feature: update Clinic model

- src/main/java/com/medspace/application/service/ClinicService.java
- src/main/java/com/medspace/application/usecase/clinic/GetAllClinicsUseCase.java
- src/main/java/com/medspace/application/usecase/clinic/GetClinicByIdUseCase.java
- src/main/java/com/medspace/application/usecase/clinic/GetFilteredClinicsUseCase.java
- src/main/java/com/medspace/domain/repository/ClinicRepository.java
- src/main/java/com/medspace/infrastructure/dto/clinic/ClinicQueryDTO.java
- src/main/java/com/medspace/infrastructure/dto/clinic/ClinicQueryFilterDTO.java
- src/main/java/com/medspace/infrastructure/repository/ClinicRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/rest/ClinicController.java
This PR introduces query filters for the GET /clinics endpoint, so that the user can filter by city, hour, date and equipment
Sample request
GET /clinics?hour=13:00
GET /clinics?city=MONTERREY
GET /clinics?equipmentList=X_RAY&equipmentList=ULTRASOUND
> Feature: Add query clinic filters

- src/main/java/com/medspace/application/usecase/user/CreateUserUseCase.java
- src/main/java/com/medspace/domain/model/User.java
- src/main/java/com/medspace/infrastructure/dto/rentRequest/GetRentRequestPreviewDTO.java
- src/main/java/com/medspace/infrastructure/dto/user/CreateUserDTO.java
- src/main/java/com/medspace/infrastructure/entity/UserEntity.java
- src/main/java/com/medspace/infrastructure/mapper/UserMapper.java
- src/main/java/com/medspace/infrastructure/rest/UserController.java
- src/main/resources/import.sql
This PR refactors the User model and related components to improve profile management functionality:
- **Renamed fields**:
- `profilePictureUrl` → `pfpPath`
- `tenantProfessionalLicenseUrl` → `tenantLicensePath`
- **Simplified file handling**:
- Removed multipart form data processing in the controller
- Eliminated direct file upload handling in `CreateUserUseCase`
- Updated DTOs to use paths instead of file streams
- **Controller updates**:
- Changed content type from `MULTIPART_FORM_DATA` to `application/json`
- Simplified user creation flow by removing file upload logic
- **Other improvements**:
- Added `bio` field to User model
- Updated relevant mappers and entities to reflect the new field structure
- Fixed references in dependent components (like `GetRentRequestPreviewDTO`)
>  User Model Refactoring for Profile Management

- src/main/java/com/medspace/application/service/UserService.java
- src/main/java/com/medspace/application/usecase/user/EditUserProfileByIdUseCase.java
- src/main/java/com/medspace/domain/repository/UserRepository.java
- src/main/java/com/medspace/infrastructure/dto/user/EditUserDTO.java
- src/main/java/com/medspace/infrastructure/repository/UserRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/rest/UserController.java
This PR implements user profile editing functionality, allowing users to update their profile information through a dedicated endpoint. The implementation includes backend validation and support for both general user fields and tenant-specific fields.
- Added endpoint for users to edit their own profiles (`PUT /users/me`)
- Implemented field-by-field update to ensure only provided fields are modified
- Added validation for all editable user profile fields
- Added special handling for tenant-specific fields (specialty and license)
- `EditUserDTO.java` - Data transfer object for profile update requests
- `EditUserProfileByIdUseCase.java` - Business logic for profile updates
- `UserRepository.java` - Added interface method for user updates
- `UserRepositoryImpl.java` - Implemented user …
> feature(user): implement user profile editing functionality and endpoint

- src/main/java/com/medspace/application/usecase/rent/GetRentRequestsByLandlordIdUseCase.java
- src/main/java/com/medspace/infrastructure/dto/rentRequest/GetRentRequestPreviewDTO.java
This PR updates the RentRequestPreviewDTO to match the frontend expected type
> Feature: Update request dto

- src/main/java/com/medspace/application/service/RentService.java
- src/main/java/com/medspace/application/usecase/rent/GetRentRequestsByUserId.java
- src/main/java/com/medspace/domain/repository/RentRequestRepository.java
- src/main/java/com/medspace/infrastructure/dto/rentRequest/GetRentRequestPreviewDTO.java
- src/main/java/com/medspace/infrastructure/dto/rentRequest/RentRequestQueryFilterDTO.java
- src/main/java/com/medspace/infrastructure/repository/RentRequestRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/rest/RentRequestController.java
This PR updates the RentRequestPreviewDTO so that it also contains the clinic availabilities, to be used by the frontend.
> Feature: Update rent request preview DTO

- src/main/java/com/medspace/application/service/ClinicService.java
- src/main/java/com/medspace/application/usecase/clinic/GetTotalClinicsCountUseCase.java
- src/main/java/com/medspace/domain/repository/ClinicRepository.java
- src/main/java/com/medspace/infrastructure/entity/ClinicEntity.java
- src/main/java/com/medspace/infrastructure/repository/ClinicRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/rest/ClinicController.java
This pull request integrates the use of PanacheRepositoryBase directly into the ClinicRepositoryImpl class. It also includes adjustments to ensure repository operations such as persist, findById, and delete are handled directly within the implementation class.
Implemented PanacheRepositoryBase<ClinicEntity, Long> in ClinicRepositoryImpl.
Created new endpoint 
/clinics/clinics-count
> add count all clinics endpoint

- src/main/java/com/medspace/application/service/UserService.java
- src/main/java/com/medspace/application/usecase/user/GetTenantCountUseCase.java
- src/main/java/com/medspace/domain/repository/UserRepository.java
- src/main/java/com/medspace/infrastructure/repository/UserRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/rest/UserController.java
Added logic for count all specialist endpoint, only available for analyst.
> add specialist count endpoint for analyst

- src/main/java/com/medspace/application/service/ClinicService.java
- src/main/java/com/medspace/application/service/UserService.java
- src/main/java/com/medspace/application/usecase/clinic/GetClinicCountByCategoryUseCase.java
- src/main/java/com/medspace/application/usecase/user/GetSpecialistCountBySpecialtyUseCase.java
- src/main/java/com/medspace/domain/repository/ClinicRepository.java
- src/main/java/com/medspace/domain/repository/UserRepository.java
- src/main/java/com/medspace/infrastructure/repository/ClinicRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/repository/UserRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/rest/ClinicController.java
- src/main/java/com/medspace/infrastructure/rest/UserController.java
> Add endpoints to count clinics by category and tenants by specialty

- src/main/java/com/medspace/application/service/ExternalClinicService.java
- src/main/java/com/medspace/application/usecase/externalClinic/GetExternalClinicsDashboardUseCase.java
- src/main/java/com/medspace/application/usecase/externalClinic/LoadExternalClinicsUseCase.java
- src/main/java/com/medspace/application/usecase/externalClinic/UpdateExternalClinicSpecialtiesUseCase.java
- src/main/java/com/medspace/domain/model/ExternalClinic.java
- src/main/java/com/medspace/domain/repository/ExternalClinicRepository.java
- src/main/java/com/medspace/infrastructure/client/ExternalClinicApiClient.java
- src/main/java/com/medspace/infrastructure/dto/common/PaginationDTO.java
- src/main/java/com/medspace/infrastructure/dto/externalClinic/ExternalClinicResponseDTO.java
- src/main/java/com/medspace/infrastructure/dto/externalClinic/GetExternalClinicSpecialistsDashboardDTO.java
- src/main/java/com/medspace/infrastructure/entity/ExternalClinicEntity.java
- src/main/java/com/medspace/infrastructure/mapper/ExternalClinicMapper.java
- src/main/java/com/medspace/infrastructure/mapper/ExternalClinicResponseMapper.java
- src/main/java/com/medspace/infrastructure/repository/ExternalClinicRepositoryImpl.java
- src/main/java/com/medspace/infrastructure/rest/ExternalClinicController.java
- src/main/java/com/medspace/infrastructure/util/SpecialtyDetector.java
- src/main/resources/application.properties
**Purpose:**
This PR introduces a comprehensive integration with the INEGI Denue API to fetch, store, and display data for external private medical clinics. This enhances our platform by providing users with access to a broader range of clinic information. The integration also includes a mechanism to infer medical specialties from clinic names.
**Key Features & Components:**
*   **Configuration (`application.properties`):**
*   The API token for the INEGI Denue service is now managed via the `external.clinic.client.token` property.
*   This token is expected to be provided through the `EXTERNAL_CLINIC_CLIENT_TOKEN` environment variable. This is crucial for security and flexibility across environments (local development and cloud).
*   For local development, ensure …
> Feature data process

- docker-compose.yml
- src/main/resources/application.properties
As title, add env to fix backend dev
> fix: add env variable to docker compose

- src/test/java/com/medspace/application/service/ClinicServiceTest.java
As title, add unit testing for clinic service
> test: add tests for clinic service

- src/test/java/com/medspace/application/service/NotificationServiceTest.java
- src/test/java/com/medspace/infrastructure/NotificationRestTest.java
> Add unit tests for NotificationService and NotificationRest
